### PR TITLE
Suggested fix and improvement

### PR DESCRIPTION
**Pull request by BeFiveINFO**
Please review if these commits are okay. Thank you.

### CODE REVIEW

**Comment by danrossi** [comment]
Thanks for that. This is just an old tool demo. You are welcome to improve it. It was data to be used with a loudness video player plugin  to replicate what Youtube is doing. at -16 lufs as the target.

**Comment by BeFiveINFO** [comment]
Thank you very much :) Your script is very helpful!

**Comment by danrossi** [comment]
That's ok not a problem. As far as implementation goes. This is what I came up with. I might open source this plugin project. 

Basically the best option you have with controlling playback, is fraction calculations between 0 and 1 to control volume using the lufs data. This is what youtube does. 

there might be even fancier ways using the audio api that can manipulate the audio in a video. 

I looked into it but didn't get far. 

https://flowplayer.electroteque.org/loudness

**Comment by danrossi** [comment]
Here is the gain factor method. you give it the lufs reading. and then it will provide a factor from the target ie -16. If the measurement from the tool says -5 which is pretty standard, it will provide a huge factor to reduce the volume. 

```
function gainFactor(iLUFS)
    {
        var lufs = Math.min((config.target - iLUFS), 0);
        return Math.pow(10, lufs / 20);
    }
```
```
gain = gainFactor(lufs);
const newVolume = gain * currentVolume;
```

**Comment by BeFiveINFO** [comment]
Actually, I tried your script from the production side of the story. 

There was someone who posted in [a forum of an audio stock site](https://forums.envato.com/t/lets-put-an-end-to-this-loudness-war-now-shall-we/178032) about loudness war. He suggest that our tracks should comform to the new standards of loudness so that we can maintain the quality of our products sold on the audio stock site. The debate still continues.

**Comment by danrossi** [comment]
oh ok not a problem you are measuring your source audio files. What project is this for , just curious ? 

The person doesn't know what they are talking about from the sounds of it, "weak" means dynamic. They just need to turn their system volume up !  

When I am mastering a sound project for film / doco. I have the meters showing -16 lufs for online delivery. Maybe you can get away with -14lufs. Other playback methods for tv require -24 or -27. 

-16 brings stuff up for portable speaker playback obviously !  This would be incredibly loud if played in a cinema theatre for instance haha. 

For music -14 to -10lufs is a good range for me especially when playing them back as a listener. I know straight away when something is too hot, I play back using my genelecs alot and I have to turn down the monitor controller ! 

For sound fx and atmos there shouldn't really be any loudness or mastering put on them. These would be done in a final mix of a project it's in ! They should stay untouched apart from light noise reduction and fine editing.

**Comment by danrossi** [comment]
the playback loudness control that I have directed it to is for video playback in playlists of a web player like youtube. Maybe the same could be applied for the playback non-transient audio files like music, podcasts and sound recordings !

**Comment by BeFiveINFO** [comment]
>>What project is this for , just curious ?

It is not really a project. I just want to check up loudness of audio files I submit to a stock music agency. I analyzed Google search trends and I found that there are now so many people who want stock music for youtube. So I want to make music for youtube.

I want to make sure that my customers can enjoy my music when they use for their youtube videos.

**Comment by danrossi** [comment]
Oh of course. "stock music" make it sit around -14 to -8 lufs like normal music ? This doesn't follow online video spec.  -5 for music is very hot. -14 is a range where it's the most dynamic and requires bringing up volumes I guess. 

This would go into other projects and then , mixed and mastered on top again. ie if I was taking your track to put into a sound mix project. this would be mixed and mastered back to -16 with the other elements.

**Comment by BeFiveINFO** [comment]
What LUFS is the best target for stock audio tracks?

**Comment by danrossi** [comment]
stock music as in longer than a few mins, -14 to -8 ? loudness is an "over time" thing. 

I have a reference level generally and use ears too. Waves WLM is still useful for music stems as a loudness meter. A realtime plugin is helpful but this tool can be useful as checking after also.

**Comment by BeFiveINFO** [comment]
>>stock music as in longer than a few mins
Around 30 seconds to 4~6 mins. We sometimes provide different variations.

Thank you very much for your insights!

**Comment by danrossi** [comment]
I would only worry about 4-6 mins. something 30 seconds is barely enough time for meters to sample and measure etc. Being short just set a reference playback level, watch peak db readings with lots of headroom maybe max -2 ??   and use your ears if it matches everything else I guess.

**Comment by BeFiveINFO** [comment]
Okay, thank you for yet more important advice! 
Have a nice weekend!

**Pull request merged**
